'use client'

import { FormEvent, useEffect, useState } from 'react'

type Opportunity = { id: string; title: string; demand_summary?: string; source_url?: string; confidence?: number; proposed_supplier?: { business_name?: string }; proposed_product?: { name?: string } }
type DashboardData = { opportunities: Opportunity[]; metrics: { suppliers: number; activePromotions: number; successfulPayments: number; queuedTasks: number } }

export default function Dashboard() {
  const [data, setData] = useState<DashboardData | null>(null)
  const [message, setMessage] = useState('')
  const [demandSignal, setDemandSignal] = useState('')
  async function load() { const response = await fetch('/api/dashboard'); if (response.ok) setData(await response.json()); else setMessage('The dashboard could not connect to the main control API.') }
  useEffect(() => { load() }, [])
  async function queueDiscovery(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage('Queuing research…'); const response = await fetch('/api/dashboard', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'queue-discovery', demandSignal }) }); setMessage(response.ok ? 'Research queued. The automation worker will process it when configured.' : 'Could not queue research.'); if (response.ok) setDemandSignal(''); await load() }
  async function runAutomation() { setMessage('Running one automation task…'); const response = await fetch('/api/dashboard', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'run-automation' }) }); const result = await response.json().catch(() => ({})); setMessage(response.ok ? (result.processed ? 'Automation task completed. Review the results below.' : 'There are no queued automation tasks.') : (result.error || 'Automation could not run.')); await load() }
  async function approve(opportunityId: string) { setMessage('Approving opportunity…'); const response = await fetch('/api/dashboard', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'approve-opportunity', opportunityId }) }); setMessage(response.ok ? 'Opportunity approved.' : 'Approval failed.'); await load() }
  const cards = data ? [['Suppliers', data.metrics.suppliers], ['Active promotions', data.metrics.activePromotions], ['Successful payments', data.metrics.successfulPayments], ['Automation queue', data.metrics.queuedTasks]] : []
  return <main className="mx-auto max-w-7xl px-5 py-10"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-semibold text-green">CONNECTNETWORK</p><h1 className="text-3xl font-bold">Operations dashboard</h1><p className="mt-2 text-slate-600">Review important decisions while automation handles repeatable work.</p></div><div className="flex gap-3"><button onClick={runAutomation} className="rounded-lg bg-green px-4 py-2 text-sm font-semibold text-white">Run automation now</button><a className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium" href={process.env.NEXT_PUBLIC_WEBSITE_URL || 'http://localhost:3000'}>View public site</a></div></header><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <article className="rounded-xl border bg-white p-5 shadow-sm" key={String(label)}><p className="text-sm text-slate-600">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</section><section className="mt-8 grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><form onSubmit={queueDiscovery} className="rounded-xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Research a demand signal</h2><p className="mt-2 text-sm text-slate-600">Ask the OpenAI worker to prepare an opportunity for your review.</p><textarea required minLength={10} value={demandSignal} onChange={event => setDemandSignal(event.target.value)} className="mt-5 min-h-32 w-full rounded-lg border p-3" placeholder="Example: affordable backup power for small South African businesses" /><button className="mt-4 rounded-lg bg-navy px-4 py-2 font-semibold text-white">Queue research</button></form><section><h2 className="text-xl font-bold">Ready for review</h2><div className="mt-4 grid gap-4">{data?.opportunities.map(item => <article className="rounded-xl border bg-white p-5 shadow-sm" key={item.id}><div className="flex flex-wrap justify-between gap-4"><div><h3 className="font-bold">{item.title}</h3><p className="mt-2 text-sm text-slate-600">{item.demand_summary || 'No demand summary provided.'}</p><p className="mt-3 text-sm">Supplier: {item.proposed_supplier?.business_name || 'Not prepared'} · Product: {item.proposed_product?.name || 'Not prepared'}</p>{item.source_url && <a className="mt-3 inline-block text-sm text-navy underline" href={item.source_url} target="_blank" rel="noreferrer">Open research source</a>}</div><button onClick={() => approve(item.id)} className="h-fit rounded-lg bg-green px-4 py-2 font-semibold text-white">Approve</button></div></article>)}{data && data.opportunities.length === 0 && <p className="rounded-xl border bg-white p-5 text-slate-600">No opportunities are waiting for approval.</p>}</div></section></section>{message && <p className="mt-6 text-sm" role="status">{message}</p>}</main>
}
